### ISSUE TITLE
CI: Go installed in different ways

### ISSUE THREAD

**Issue by winwisely99** [getcouragenow/packages#331]
The CI files install golang in many different ways.

All here:
https://github.com/getcouragenow/packages/tree/master/.github/workflows

Also the env variables also. They are exported again and again in each step. 

This is going to give us weird issues later.

E.G: build-sign-deploy-desktop.yml, plus the others.

WRONG
````
env:
      GOROOT: /usr/local/go
      GO111MODULE: auto
    steps:
      - name: Install Go
        run: |
          sudo apt-get update
          wget -q https://dl.google.com/go/go1.13.linux-amd64.tar.gz -O /tmp/go_install.tar.gz
          sudo tar -C /usr/local -xzf /tmp/go_install.tar.gz
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
          go version
````

CORRECT:

````

    env:
      GO111MODULE: auto
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1

```

Also comment out the Signing Or just turn off those actions. DONT delete them !
This is so that the artifacts are released to github releases and we know that the changes done are working.
